/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ApiPublicLeadsRouteImport } from './routes/api/public/leads'
import { Route as ApiPublicDiagnosticoRouteImport } from './routes/api/public/diagnostico'

const AuthenticatedIndexLazyRouteImport = createFileRoute('/_authenticated/')()
const AuthenticatedTarefasLazyRouteImport = createFileRoute(
  '/_authenticated/tarefas',
)()
const AuthenticatedRegrasAtivacaoLazyRouteImport = createFileRoute(
  '/_authenticated/regras-ativacao',
)()
const AuthenticatedPipelineLazyRouteImport = createFileRoute(
  '/_authenticated/pipeline',
)()
const AuthenticatedEstrategiaLazyRouteImport = createFileRoute(
  '/_authenticated/estrategia',
)()
const AuthenticatedConfiguracoesLazyRouteImport = createFileRoute(
  '/_authenticated/configuracoes',
)()
const AuthenticatedCockpitLazyRouteImport = createFileRoute(
  '/_authenticated/cockpit',
)()
const AuthenticatedCategoriasLazyRouteImport = createFileRoute(
  '/_authenticated/categorias',
)()
const AuthenticatedAgendaLazyRouteImport = createFileRoute(
  '/_authenticated/agenda',
)()
const AuthenticatedClientesIndexLazyRouteImport = createFileRoute(
  '/_authenticated/clientes/',
)()
const AuthenticatedClientesIdLazyRouteImport = createFileRoute(
  '/_authenticated/clientes/$id',
)()

const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/auth.lazy').then((d) => d.Route))
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/_authenticated/route.lazy').then((d) => d.Route),
)
const AuthenticatedIndexLazyRoute = AuthenticatedIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/index.lazy').then((d) => d.Route),
)
const AuthenticatedTarefasLazyRoute =
  AuthenticatedTarefasLazyRouteImport.update({
    id: '/tarefas',
    path: '/tarefas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/tarefas.lazy').then((d) => d.Route),
  )
const AuthenticatedRegrasAtivacaoLazyRoute =
  AuthenticatedRegrasAtivacaoLazyRouteImport.update({
    id: '/regras-ativacao',
    path: '/regras-ativacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/regras-ativacao.lazy').then((d) => d.Route),
  )
const AuthenticatedPipelineLazyRoute =
  AuthenticatedPipelineLazyRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/pipeline.lazy').then((d) => d.Route),
  )
const AuthenticatedEstrategiaLazyRoute =
  AuthenticatedEstrategiaLazyRouteImport.update({
    id: '/estrategia',
    path: '/estrategia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/estrategia.lazy').then((d) => d.Route),
  )
const AuthenticatedConfiguracoesLazyRoute =
  AuthenticatedConfiguracoesLazyRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/configuracoes.lazy').then((d) => d.Route),
  )
const AuthenticatedCockpitLazyRoute =
  AuthenticatedCockpitLazyRouteImport.update({
    id: '/cockpit',
    path: '/cockpit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/cockpit.lazy').then((d) => d.Route),
  )
const AuthenticatedCategoriasLazyRoute =
  AuthenticatedCategoriasLazyRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/categorias.lazy').then((d) => d.Route),
  )
const AuthenticatedAgendaLazyRoute = AuthenticatedAgendaLazyRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/agenda.lazy').then((d) => d.Route),
)
const AuthenticatedClientesIndexLazyRoute =
  AuthenticatedClientesIndexLazyRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/clientes/index.lazy').then((d) => d.Route),
  )
const AuthenticatedClientesIdLazyRoute =
  AuthenticatedClientesIdLazyRouteImport.update({
    id: '/clientes/$id',
    path: '/clientes/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/clientes/$id.lazy').then((d) => d.Route),
  )
const ApiPublicLeadsRoute = ApiPublicLeadsRouteImport.update({
  id: '/api/public/leads',
  path: '/api/public/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiagnosticoRoute = ApiPublicDiagnosticoRouteImport.update({
  id: '/api/public/diagnostico',
  path: '/api/public/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexLazyRoute
  '/auth': typeof AuthRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/agenda': typeof AuthenticatedAgendaLazyRoute
  '/categorias': typeof AuthenticatedCategoriasLazyRoute
  '/cockpit': typeof AuthenticatedCockpitLazyRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesLazyRoute
  '/estrategia': typeof AuthenticatedEstrategiaLazyRoute
  '/pipeline': typeof AuthenticatedPipelineLazyRoute
  '/regras-ativacao': typeof AuthenticatedRegrasAtivacaoLazyRoute
  '/tarefas': typeof AuthenticatedTarefasLazyRoute
  '/api/public/diagnostico': typeof ApiPublicDiagnosticoRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/clientes/$id': typeof AuthenticatedClientesIdLazyRoute
  '/clientes/': typeof AuthenticatedClientesIndexLazyRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/agenda': typeof AuthenticatedAgendaLazyRoute
  '/categorias': typeof AuthenticatedCategoriasLazyRoute
  '/cockpit': typeof AuthenticatedCockpitLazyRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesLazyRoute
  '/estrategia': typeof AuthenticatedEstrategiaLazyRoute
  '/pipeline': typeof AuthenticatedPipelineLazyRoute
  '/regras-ativacao': typeof AuthenticatedRegrasAtivacaoLazyRoute
  '/tarefas': typeof AuthenticatedTarefasLazyRoute
  '/': typeof AuthenticatedIndexLazyRoute
  '/api/public/diagnostico': typeof ApiPublicDiagnosticoRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/clientes/$id': typeof AuthenticatedClientesIdLazyRoute
  '/clientes': typeof AuthenticatedClientesIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaLazyRoute
  '/_authenticated/categorias': typeof AuthenticatedCategoriasLazyRoute
  '/_authenticated/cockpit': typeof AuthenticatedCockpitLazyRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesLazyRoute
  '/_authenticated/estrategia': typeof AuthenticatedEstrategiaLazyRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineLazyRoute
  '/_authenticated/regras-ativacao': typeof AuthenticatedRegrasAtivacaoLazyRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasLazyRoute
  '/_authenticated/': typeof AuthenticatedIndexLazyRoute
  '/api/public/diagnostico': typeof ApiPublicDiagnosticoRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/_authenticated/clientes/$id': typeof AuthenticatedClientesIdLazyRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/diagnostico'
    | '/agenda'
    | '/categorias'
    | '/cockpit'
    | '/configuracoes'
    | '/estrategia'
    | '/pipeline'
    | '/regras-ativacao'
    | '/tarefas'
    | '/api/public/diagnostico'
    | '/api/public/leads'
    | '/clientes/$id'
    | '/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/diagnostico'
    | '/agenda'
    | '/categorias'
    | '/cockpit'
    | '/configuracoes'
    | '/estrategia'
    | '/pipeline'
    | '/regras-ativacao'
    | '/tarefas'
    | '/'
    | '/api/public/diagnostico'
    | '/api/public/leads'
    | '/clientes/$id'
    | '/clientes'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/diagnostico'
    | '/_authenticated/agenda'
    | '/_authenticated/categorias'
    | '/_authenticated/cockpit'
    | '/_authenticated/configuracoes'
    | '/_authenticated/estrategia'
    | '/_authenticated/pipeline'
    | '/_authenticated/regras-ativacao'
    | '/_authenticated/tarefas'
    | '/_authenticated/'
    | '/api/public/diagnostico'
    | '/api/public/leads'
    | '/_authenticated/clientes/$id'
    | '/_authenticated/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  ApiPublicDiagnosticoRoute: typeof ApiPublicDiagnosticoRoute
  ApiPublicLeadsRoute: typeof ApiPublicLeadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/regras-ativacao': {
      id: '/_authenticated/regras-ativacao'
      path: '/regras-ativacao'
      fullPath: '/regras-ativacao'
      preLoaderRoute: typeof AuthenticatedRegrasAtivacaoLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estrategia': {
      id: '/_authenticated/estrategia'
      path: '/estrategia'
      fullPath: '/estrategia'
      preLoaderRoute: typeof AuthenticatedEstrategiaLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cockpit': {
      id: '/_authenticated/cockpit'
      path: '/cockpit'
      fullPath: '/cockpit'
      preLoaderRoute: typeof AuthenticatedCockpitLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categorias': {
      id: '/_authenticated/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AuthenticatedCategoriasLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthenticatedClientesIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/$id': {
      id: '/_authenticated/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/leads': {
      id: '/api/public/leads'
      path: '/api/public/leads'
      fullPath: '/api/public/leads'
      preLoaderRoute: typeof ApiPublicLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/diagnostico': {
      id: '/api/public/diagnostico'
      path: '/api/public/diagnostico'
      fullPath: '/api/public/diagnostico'
      preLoaderRoute: typeof ApiPublicDiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaLazyRoute: typeof AuthenticatedAgendaLazyRoute
  AuthenticatedCategoriasLazyRoute: typeof AuthenticatedCategoriasLazyRoute
  AuthenticatedCockpitLazyRoute: typeof AuthenticatedCockpitLazyRoute
  AuthenticatedConfiguracoesLazyRoute: typeof AuthenticatedConfiguracoesLazyRoute
  AuthenticatedEstrategiaLazyRoute: typeof AuthenticatedEstrategiaLazyRoute
  AuthenticatedPipelineLazyRoute: typeof AuthenticatedPipelineLazyRoute
  AuthenticatedRegrasAtivacaoLazyRoute: typeof AuthenticatedRegrasAtivacaoLazyRoute
  AuthenticatedTarefasLazyRoute: typeof AuthenticatedTarefasLazyRoute
  AuthenticatedIndexLazyRoute: typeof AuthenticatedIndexLazyRoute
  AuthenticatedClientesIdLazyRoute: typeof AuthenticatedClientesIdLazyRoute
  AuthenticatedClientesIndexLazyRoute: typeof AuthenticatedClientesIndexLazyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaLazyRoute: AuthenticatedAgendaLazyRoute,
  AuthenticatedCategoriasLazyRoute: AuthenticatedCategoriasLazyRoute,
  AuthenticatedCockpitLazyRoute: AuthenticatedCockpitLazyRoute,
  AuthenticatedConfiguracoesLazyRoute: AuthenticatedConfiguracoesLazyRoute,
  AuthenticatedEstrategiaLazyRoute: AuthenticatedEstrategiaLazyRoute,
  AuthenticatedPipelineLazyRoute: AuthenticatedPipelineLazyRoute,
  AuthenticatedRegrasAtivacaoLazyRoute: AuthenticatedRegrasAtivacaoLazyRoute,
  AuthenticatedTarefasLazyRoute: AuthenticatedTarefasLazyRoute,
  AuthenticatedIndexLazyRoute: AuthenticatedIndexLazyRoute,
  AuthenticatedClientesIdLazyRoute: AuthenticatedClientesIdLazyRoute,
  AuthenticatedClientesIndexLazyRoute: AuthenticatedClientesIndexLazyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  ApiPublicDiagnosticoRoute: ApiPublicDiagnosticoRoute,
  ApiPublicLeadsRoute: ApiPublicLeadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
